exclude: ["src", "node_modules", "bower.json", "bower_components/font-awesome/src", "composer.json", "package.json", "README.md", "LICENSE", "Gruntfile.js", "Gemfile"]
include: [
"amelia/_bootswatch.scss",
"amelia/_variables.scss",
"cerulean/_bootswatch.scss",
"cerulean/_variables.scss",
"cosmo/_bootswatch.scss",
"cosmo/_variables.scss",
"cyborg/_bootswatch.scss",
"cyborg/_variables.scss",
"darkly/_bootswatch.scss",
"darkly/_variables.scss",
"flatly/_bootswatch.scss",
"flatly/_variables.scss",
"journal/_bootswatch.scss",
"journal/_variables.scss",
"lumen/_bootswatch.scss",
"lumen/_variables.scss",
"paper/_bootswatch.scss",
"paper/_variables.scss",
"readable/_bootswatch.scss",
"readable/_variables.scss",
"sandstone/_bootswatch.scss",
"sandstone/_variables.scss",
"simplex/_bootswatch.scss",
"simplex/_variables.scss",
"slate/_bootswatch.scss",
"slate/_variables.scss",
"spacelab/_bootswatch.scss",
"spacelab/_variables.scss",
"superhero/_bootswatch.scss",
"superhero/_variables.scss",
"united/_bootswatch.scss",
"united/_variables.scss",
"yeti/_bootswatch.scss",
"yeti/_variables.scss",
"custom/_bootswatch.scss",
"custom/_variables.scss"
]
